### ISSUE TITLE
Implement PKCE Flow for OAuth 2.0 in Mock API

### ISSUE THREAD

**Issue by dtinth** [dtinth/mockapis#2]
We need to implement the Proof Key for Code Exchange (PKCE) flow in our mock OAuth 2.0 API. This enhancement will allow our mock API to better simulate real-world OAuth 2.0 providers and help developers test their applications more effectively.

### Tasks:
1. Implement the PKCE flow as described in the [OAuth 2.0 PKCE guide](https://oauth.net/2/pkce/). This involves:
   - Generating a code verifier and its corresponding code challenge.
   - Modifying the authorization endpoint to accept the `code_challenge` parameter.
   - Ensuring that the token endpoint verifies the `code_verifier` parameter during the authorization code exchange.
2. Update the existing authorization code flow to support PKCE.
3. Write tests to ensure the PKCE flow is working correctly.

### Resources:
- [OAuth 2.0 PKCE Guide](https://oauth.net/2/pkce/)
- [Understanding and using OAuth as a frontend developer](https://www.youtube.com/watch?v=g8WHD5F5hvo) - Zell Liew

### Acceptance Criteria:
- The PKCE flow is fully implemented and integrated with the existing OAuth 2.0 endpoints.
- All tests pass successfully.
- Documentation is updated to reflect the new PKCE flow.

### Notes:
Feel free to ask questions or request clarification if needed. Contributions are highly appreciated!

Thank you!

**Comment by icegotcha** [comment]
Can I work on this issue? 🤗

**Comment by icegotcha** [comment]
@dtinth I have a question.

 Can I use 'View' to store temporary data (stored from an API and used in another API)?

**Comment by dtinth** [comment]
@icegotcha Hmm, I prefer the system to be as stateless as possible.

Maybe you can adjust `generateAuthorizationCode` to include `code_challenge` and `code_challenge_method` inside the generated token. Then in the `POST /protocol/openid-connect/token` endpoint can extract it from the authorization code. (Note that this approach is insecure, only good for mock APIs, and should never be used in production apps.)

**Comment by icegotcha** [comment]
@dtinth 
I'll give it a try. Thank you so much!
