### ISSUE TITLE
Implement streaming support for OpenAI mock API

### ISSUE THREAD

**Issue by dtinth** [dtinth/mockapis#4]
### Issue Description
The current OpenAI mock API does not support streaming responses for chat completions. Streaming is an essential feature for many real-time applications, and adding this functionality will make the mock API more useful for developers who want to simulate real-world scenarios more accurately.

### Tasks
1. Implement a streaming endpoint for chat completions in the OpenAI mock API.
2. Update existing tests and add new tests to cover the streaming functionality.

### Resources
- [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat)
- [OpenAI Streaming Guide](https://platform.openai.com/docs/api-reference/streaming)
- [Elysia Documentation](https://elysiajs.com/docs)

### Acceptance Criteria
- A new streaming endpoint is available in the OpenAI mock API.
- All tests pass successfully.

**Comment by moudgalya1223** [comment]
Can we start working

**Comment by dtinth** [comment]
@moudgalya1223 Thanks, assigned to you!

**Comment by moudgalya1223** [comment]
hello @dtinth  can you help me out with requiremnt with any docs

**Comment by dtinth** [comment]
@moudgalya1223 sorry, i am unable to provide a guide as i don't have enough time ;-;. maybe you can ask in ElysiaJS Discord server or your local dev community for guidance on how to implement streaming. also check out the resources linked from the issue description.

let me know if you still would like to work on this issue.

**Comment by mewxz029** [comment]
Maybe I should ask to work on it ?

**Comment by dtinth** [comment]
@mewxz029 sure, thanks very much, please go ahead krub!
